import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'vite';import {getPlatformProxy} from 'wrangler';
const server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});
const {submitLead,validateLead,hash}=await server.ssrLoadModule('/src/lib/server/leads.ts');
const {catalog,canPublish,isPreview,bundle}=await server.ssrLoadModule('/src/lib/server/content.ts');
const proxy=await getPlatformProxy({configPath:'wrangler.jsonc'});const db=proxy.env.LEADS_DB;
const url=new URL('http://127.0.0.1:5173/resources/accessibility');const env={...proxy.env,MAIL_MODE:'capture'};const run=crypto.randomUUID().slice(0,8);
const form=(email,updates=false)=>{const f=new FormData();f.set('email',email);f.set('privacy','yes');f.set('role','developer');if(updates)f.set('updates','yes');return f;};
const rows=async(sql,...bindings)=>(await db.prepare(sql).bind(...bindings).all()).results;
test.after(async()=>{await db.prepare("DELETE FROM leads WHERE email LIKE ?").bind('qa-'+run+'-%@example.test').run();await proxy.dispose();await server.close();});
test('validation rejects malformed email, unrecognized role and missing consent',()=>{assert.ok(validateLead(form('bad')).error);const f=form('okay@example.test');f.delete('privacy');assert.ok(validateLead(f).error);f.set('privacy','yes');f.set('role','admin');assert.ok(validateLead(f).error);f.set('role','');f.set('company_url','spam');assert.ok(validateLead(f).error);});
test('drafts are available only in local preview; public bundles exclude all drafts',()=>{assert.equal(isPreview(url),true);assert.equal(isPreview(new URL('https://jangwook.net')),false);assert.equal(catalog.filter(canPublish).length,3);assert.ok(bundle(false).includes(catalog.find(p=>p.slug==='non-text-content').prompt));assert.ok(!bundle(false).includes(catalog.find(p=>p.slug==='keyboard').prompt));assert.ok(bundle(true).includes(catalog.find(p=>p.slug==='keyboard').prompt));});
test('lead, optional consent and captured mail persist; duplicate request creates no second mail',async()=>{const email='qa-'+run+'-one@example.test';const first=await submitLead(form(email,true),url,env,run+'one');assert.equal(first.ok,true);assert.equal(first.captured,true);const second=await submitLead(form(email,true),url,env,run+'one');assert.equal(second.duplicate,true);const lead=await db.prepare('SELECT id,verified_at FROM leads WHERE email=?').bind(email).first();assert.equal(lead.verified_at,null);const requests=await rows('SELECT r.id,o.body,o.status FROM material_requests r JOIN mail_outbox o ON o.request_id=r.id WHERE r.lead_id=?',lead.id);assert.equal(requests.length,1);assert.equal(requests[0].status,'captured');const confirm=requests[0].body.match(/\/confirm\/([a-f0-9]{64})/)[1];assert.ok(await db.prepare('SELECT id FROM material_requests WHERE token_hash=?').bind(await hash(confirm)).first());const stop=requests[0].body.match(/\/unsubscribe\/([a-f0-9]{64})/)[1];assert.ok(await db.prepare('SELECT lead_id FROM management_tokens WHERE token_hash=?').bind(await hash(stop)).first());assert.equal((await rows('SELECT granted FROM lead_consents WHERE lead_id=?',lead.id))[0].granted,1);});
test('concurrent submissions produce one request and one captured outbox',async()=>{const email='qa-'+run+'-race@example.test';const results=await Promise.all([submitLead(form(email),url,env,run+'race'),submitLead(form(email),url,env,run+'race')]);assert.ok(results.every(r=>r.ok));const records=await rows('SELECT o.id FROM mail_outbox o JOIN material_requests r ON r.id=o.request_id JOIN leads l ON l.id=r.lead_id WHERE l.email=?',email);assert.equal(records.length,1);});
test('rate limit stops the sixth request',async()=>{for(let i=0;i<5;i++){const result=await submitLead(form('qa-'+run+'-limit'+i+'@example.test'),url,env,run+'limit');assert.equal(result.ok,true);}const blocked=await submitLead(form('qa-'+run+'-limit6@example.test'),url,env,run+'limit');assert.equal(blocked.ok,false);assert.match(blocked.error,/한 시간/);});
test('public draft submission and nonlocal capture cannot create leads',async()=>{const email='qa-'+run+'-public@example.test';const result=await submitLead(form(email),new URL('https://jangwook.net/resources/accessibility'),env,run+'public');assert.equal(result.ok,false);assert.equal((await rows('SELECT id FROM leads WHERE email=?',email)).length,0);});
test('provider acceptance records a receipt and attaches approved prompts; failures stay distinct',async()=>{const saved=catalog.map(p=>({...p}));for(const post of catalog)Object.assign(post,{status:'published',approvalHash:post.sourceHash,reviewedAt:new Date(Date.now()-20000).toISOString(),publishedAt:new Date(Date.now()-10000).toISOString()});try{let sent;const provider={...env,MAIL_MODE:'cloudflare',SITE_URL:'https://jangwook.net',FROM_EMAIL:'materials@jangwook.net',EMAIL:{send:async message=>{sent=message;return{messageId:'mock-provider-receipt'};}}};const remote=new URL('https://jangwook.net/resources/accessibility');const email='qa-'+run+'-provider@example.test';const accepted=await submitLead(form(email),remote,provider,run+'provider');assert.equal(accepted.ok,true);assert.equal(accepted.captured,false);assert.equal(sent.to,email);assert.match(Buffer.from(sent.attachments[0].content,'base64').toString('utf8'),/評価|평가/);const receipt=(await rows('SELECT o.status,o.provider_id FROM mail_outbox o JOIN material_requests r ON r.id=o.request_id JOIN leads l ON l.id=r.lead_id WHERE l.email=?',email))[0];assert.equal(receipt.status,'accepted');assert.equal(receipt.provider_id,'mock-provider-receipt');const failedEmail='qa-'+run+'-failed@example.test';const failed=await submitLead(form(failedEmail),remote,{...provider,EMAIL:{send:async()=>{throw new Error('mock-failure');}}},run+'failed');assert.equal(failed.pending,true);const record=(await rows('SELECT o.status FROM mail_outbox o JOIN material_requests r ON r.id=o.request_id JOIN leads l ON l.id=r.lead_id WHERE l.email=?',failedEmail))[0];assert.equal(record.status,'failed');let retried=false;const repeated=await submitLead(form(failedEmail),remote,{...provider,EMAIL:{send:async()=>{retried=true;return{messageId:'unexpected'};}}},run+'failed');assert.equal(repeated.duplicate,true);assert.equal(retried,false);}finally{catalog.forEach((p,i)=>Object.assign(p,saved[i]));}});

test('expired material links can be requested again with a fresh token',async()=>{const email='qa-'+run+'-expired@example.test';await submitLead(form(email),url,env,run+'expiry');const old=(await rows('SELECT r.id,r.token_hash FROM material_requests r JOIN leads l ON l.id=r.lead_id WHERE l.email=?',email))[0];await db.prepare('UPDATE material_requests SET expires_at=? WHERE id=?').bind(Date.now()-1000,old.id).run();const refreshed=await submitLead(form(email),url,env,run+'expiry');assert.equal(refreshed.captured,true);const fresh=(await rows('SELECT r.id,r.token_hash FROM material_requests r JOIN leads l ON l.id=r.lead_id WHERE l.email=?',email))[0];assert.notEqual(fresh.id,old.id);assert.notEqual(fresh.token_hash,old.token_hash);});
test('changed content, invalid approval dates and future publication remain private',()=>{const post={...catalog[0],status:'published',approvalHash:catalog[0].sourceHash,reviewedAt:new Date(Date.now()-20000).toISOString(),publishedAt:new Date(Date.now()-10000).toISOString()};assert.equal(canPublish(post),true);assert.equal(canPublish({...post,approvalHash:'0'.repeat(64)}),false);assert.equal(canPublish({...post,reviewedAt:'invalid'}),false);assert.equal(canPublish({...post,publishedAt:new Date(Date.now()+60000).toISOString()}),false);});

test('provider acceptance followed by database failure keeps the send claim and receipt',async()=>{const saved=catalog.map(p=>({...p}));for(const post of catalog)Object.assign(post,{status:'published',approvalHash:post.sourceHash,reviewedAt:new Date(Date.now()-20000).toISOString(),publishedAt:new Date(Date.now()-10000).toISOString()});try{let accepted=false,failedOnce=false;const faultDb={prepare:db.prepare.bind(db),batch:async statements=>{if(accepted&&!failedOnce){failedOnce=true;throw new Error('receipt-write-failure');}return db.batch(statements);}};const provider={...env,LEADS_DB:faultDb,MAIL_MODE:'cloudflare',SITE_URL:'https://jangwook.net',FROM_EMAIL:'materials@jangwook.net',EMAIL:{send:async()=>{accepted=true;return{messageId:'mock-receipt-before-db-failure'};}}};const email='qa-'+run+'-receiptfailure@example.test';const result=await submitLead(form(email),new URL('https://jangwook.net/resources/accessibility'),provider,run+'receiptfailure');assert.equal(result.pending,true);const row=(await rows('SELECT o.status,o.provider_id FROM mail_outbox o JOIN material_requests r ON r.id=o.request_id JOIN leads l ON l.id=r.lead_id WHERE l.email=?',email))[0];assert.equal(row.status,'sending');assert.equal(row.provider_id,'mock-receipt-before-db-failure');}finally{catalog.forEach((p,i)=>Object.assign(p,saved[i]));}});
