import test from 'node:test';import assert from 'node:assert/strict';
import {isMediaAsset,serveMedia} from '../worker/media-assets.ts';
const data=Uint8Array.from({length:256},(_,i)=>i);
const assets={fetch:async request=>{assert.equal(request.headers.get('Range'),null);return new Response(data,{headers:{'Content-Type':'video/mp4','ETag':'"fixed"','Cache-Control':'public, no-transform','X-Robots-Tag':'noindex, follow'}});}};
const req=(range,extra={})=>new Request('https://example.test/lab-fixtures/media-1.2.1/teaching/ko.mp4',{headers:{...(range?{Range:range}:{}),...extra}});
test('native media headers expose length and preserve source bytes',async()=>{const r=await serveMedia(req(),assets);assert.equal(r.status,200);assert.equal(r.headers.get('Content-Length'),'256');assert.equal(r.headers.get('Accept-Ranges'),'bytes');assert.equal(r.headers.get('X-Robots-Tag'),'noindex, follow');assert.deepEqual(new Uint8Array(await r.arrayBuffer()),data);});
test('prefix, suffix and open-ended ranges return the exact source interval',async()=>{for(const [range,start,end] of [['bytes=0-63',0,63],['bytes=-32',224,255],['bytes=240-',240,255],['bytes=250-999',250,255]]){const r=await serveMedia(req(range),assets);assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),`bytes ${start}-${end}/256`);assert.deepEqual(new Uint8Array(await r.arrayBuffer()),data.slice(start,end+1));}});
test('unsatisfiable ranges and validator mismatches retain HTTP semantics',async()=>{for(const range of ['bytes=300-','bytes=70-10','bytes=-0']){const r=await serveMedia(req(range),assets);assert.equal(r.status,416);assert.equal(r.headers.get('Content-Range'),'bytes */256');}const mismatch=await serveMedia(req('bytes=0-10',{'If-Range':'"old"'}),assets);assert.equal(mismatch.status,200);const match=await serveMedia(req('bytes=0-10',{'If-Range':'"fixed"'}),assets);assert.equal(match.status,206);const head=await serveMedia(new Request(req().url,{method:'HEAD'}),assets);assert.equal(head.headers.get('Content-Length'),'256');assert.equal((await head.arrayBuffer()).byteLength,0);});
test('media routing excludes HTML, unrelated paths and arbitrary language assets',()=>{assert.ok(isMediaAsset('/lab-fixtures/media-1.2.1/teaching/en.mp4'));assert.ok(isMediaAsset('/lab-fixtures/media-1.2.1/original/assets/corrupt.wav'));for(const path of ['/lab-fixtures/media-1.2.1/ko/K63.html','/about','/lab-fixtures/media-1.2.1/teaching/fr.mp4'])assert.equal(isMediaAsset(path),false);});
