export const languages = {ko:'한국어', en:'English', ja:'日本語', zh:'中文'} as const;
export type Language = keyof typeof languages;
export function isLanguage(value:string):value is Language {return Object.hasOwn(languages,value);}
export function seriesLanguage(path:string):Language {const first=path.split('/')[1];return isLanguage(first)&&/^\/(ko|en|ja|zh)(?:\/?$|\/(series|prompts|about|updates|privacy|services|labs|archive|tags|blog)(\/|$))/.test(path)?first:'ko';}
export function localizedPath(path:string,lang:Language){return path==='/'?'/'+lang+'/':lang==='ko'?path:'/'+lang+path;}
const ko={
 seriesNavigation:'시리즈 학습 탐색',currentChapter:'현재 글',
 createdDate:'초판 공개일',notPublished:'공개 예정',modifiedDate:'최종 수정일',
 preparationTitle:'이 글을 준비하고 있습니다.',preparationMessage:'본문은 집필과 검토를 마친 뒤 이 주소에 추가합니다. 전체 학습 순서에서 다룰 주제를 미리 확인할 수 있습니다.',preparationPrompt:'항목별 평가 프롬프트도 같은 글에서 제공할 예정입니다.',sourceStandard:'기준 원문 읽기',series:'시리즈',prompts:'프롬프트',tools:'도구',about:'소개',resources:'자료 받기',home:'홈',skip:'본문으로 건너뛰기',menu:'주 메뉴',archive:'아카이브',updates:'업데이트',privacy:'개인정보 안내',inbox:'로컬 메일함',language:'언어 선택',korean:'한국어',review:'로컬 편집 검토본',reviewNote:'새 시리즈의 글과 프롬프트는 발행 전 초안입니다.',
 seriesTitle:'웹 접근성',seriesDescription:'WCAG 2.2의 모든 활성 기준별 해설, 멀티모달 평가 프롬프트와 에이전트 적용.',seriesLead:'누구나 사용할 수 있는 웹을 만드는 기준. 한 항목씩 깊이 이해하고, AI로 평가하는 방법을 배웁니다.',guide:'학습 가이드',drafts:'편의 학습 과정',overviewFlow:'개요 → 기준별 해설·프롬프트 → 통합',start:'개요부터 읽기',preparing:'공개 준비 중',getPrompts:'전체 프롬프트 받기',curriculum:'학습 순서',levelFilter:'학습 수준 필터',all:'전체',public:'공개',draft:'초안',planned:'준비 중',read:'읽기',
 groups:['처음 시작하기','인지할 수 있는 웹','조작할 수 있는 웹','이해할 수 있는 웹','견고하게 연결되는 웹','서비스로 연결하기'],captions:['관점과 평가 방법을 먼저 익힙니다.','정보를 보고, 듣고, 다른 형태로 이해하기.','키보드, 포인터, 시간과 탐색의 장벽을 줄이기.','예측 가능한 동작과 입력·인증 과정.','보조 기술과 이름·역할·상태를 공유하기.','항목별 평가를 에이전트와 운영 과정으로 통합합니다.'],
 bundleHeading:'전체 프롬프트와 실행 순서가 필요하다면.',bundleAction:'모음집 받기',bundleArticleTitle:'이 프롬프트를 전체 점검 순서에 연결하세요.',bundleArticleText:'시리즈의 모든 프롬프트와 자료 준비법을 모음집으로 제공합니다.',koreanResourceNotice:'자료 신청 페이지는 현재 한국어이며, 전체 시리즈의 공개 승인 후 모음집을 제공합니다.',
 allChapters:'전체 학습 순서',version:'버전',draftDate:'2026.10.01 초안',toc:'이 글에서 배울 것',tocLabel:'이 글의 목차',evaluationPrompt:'평가 프롬프트',authorNote:'웹의 기준을 실무의 판단으로 연결합니다.',editorialDraft:'편집 초안',pagination:'시리즈 다음 학습',previous:'이전 글',next:'다음 글',
 promptTitle:'이 항목의 평가 프롬프트',copy:'프롬프트 복사',copied:'복사 완료',copySuccess:'프롬프트를 복사했습니다.',copyFailure:'자동 복사가 되지 않았습니다. 아래 텍스트를 선택해 복사해주세요.',promptHelp:'필요한 자료를 함께 입력한 뒤 실행하세요.',promptFull:'평가 프롬프트 전문',
 libraryTitle:'접근성 평가 프롬프트',libraryDescription:'WCAG 기준별로 찾아보는 멀티모달 접근성 평가 프롬프트. 입력 준비법과 결과 해석을 함께 제공합니다.',libraryLead:'각 프롬프트는 해설, 입력 자료, 결과 해석과 함께 제공합니다. 평가의 범위는 실행 사례를 통해 계속 검증합니다.',searchLabel:'프롬프트 검색',searchInput:'제목 또는 WCAG 번호로 찾기',searchPlaceholder:'예: 키보드, 대체 텍스트, 1.1.1',level:'학습 수준',search:'검색',promptCount:'개 항목',explanation:'해설과 프롬프트',empty:'검색에 맞는 프롬프트가 없습니다. 다른 제목이나 기준 번호로 찾아보세요.',
 collectionLead:'중요한 주제를 처음부터 끝까지 연결합니다. 기준과 기술이 바뀌면, 글과 프롬프트도 함께 발전합니다.',collectionSummary:'개요 · 항목별 프롬프트 · 에이전트 통합',nextTopics:'다음 주제',afterSelection:'주제 선정 후 시작합니다.',siteDescription:'웹 접근성, AI와 비즈니스를 위한 웹 교육과 실무 자료',jobTitle:'웹 개발자 · 기술 교육과 컨설팅'
};
type Labels = {[K in keyof typeof ko]: typeof ko[K] extends string[] ? string[] : string};
const en:Labels={
 seriesNavigation:'Series learning navigation',currentChapter:'Current chapter',
 createdDate:'First published',notPublished:'Not yet published',modifiedDate:'Last updated',
 preparationTitle:'This chapter is in preparation.',preparationMessage:'The article will be added at this address after writing and review. Explore the full learning order to see what is coming.',preparationPrompt:'Its evaluation prompt will be provided alongside the article.',sourceStandard:'Read the source standard',series:'Series',prompts:'Prompts',tools:'Tools',about:'About',resources:'Resources',home:'Home',skip:'Skip to main content',menu:'Main navigation',archive:'Archive',updates:'Updates',privacy:'Privacy',inbox:'Local inbox',language:'Choose language',korean:'Korean',review:'Local editorial preview',reviewNote:'New series articles and prompts are unpublished drafts.',
 seriesTitle:'Web accessibility',seriesDescription:'Explanations of every active WCAG 2.2 success criterion, multimodal evaluation prompts and agent workflows.',seriesLead:'Standards for a web everyone can use. Understand each criterion in depth and learn how to evaluate it with AI.',guide:'Study guide',drafts:'chapters',overviewFlow:'Overview → criteria and prompts → integration',start:'Start with the overview',preparing:'Preparing for publication',getPrompts:'Get all prompts',curriculum:'Learning order',levelFilter:'Conformance level filter',all:'All',public:'Published',draft:'Draft',planned:'In preparation',read:'Read',
 groups:['Getting started','A perceivable web','An operable web','An understandable web','A robust web','Connecting to a service'],captions:['Begin with the perspective and evaluation method.','Perceive information visually, aurally and in other forms.','Reduce barriers involving keyboards, pointers, time and navigation.','Predictable behavior, input and authentication.','Share names, roles and states with assistive technology.','Integrate criterion evaluations into agent workflows and operations.'],
 bundleHeading:'Need the full set of prompts and workflow?',bundleAction:'Get the collection',bundleArticleTitle:'Connect this prompt to the full evaluation workflow.',bundleArticleText:'The collection includes the series prompts and instructions for preparing evidence.',koreanResourceNotice:'The resource request page is currently in Korean. The complete collection will be available after the series is approved for publication.',
 allChapters:'All chapters',version:'Version',draftDate:'Draft · 2026-10-01',toc:'What you will learn',tocLabel:'Article contents',evaluationPrompt:'Evaluation prompt',authorNote:'Connecting web standards to practical decisions.',editorialDraft:'Editorial draft',pagination:'Series navigation',previous:'Previous article',next:'Next article',
 promptTitle:'Evaluation prompt for this topic',copy:'Copy prompt',copied:'Copied',copySuccess:'Prompt copied.',copyFailure:'Automatic copying failed. Select and copy the text below.',promptHelp:'Provide the required evidence before running the prompt.',promptFull:'Full evaluation prompt',
 libraryTitle:'Accessibility evaluation prompts',libraryDescription:'Multimodal accessibility evaluation prompts by WCAG criterion, with input preparation and interpretation.',libraryLead:'Each prompt includes an explanation, required inputs and guidance for interpreting results. Evaluation coverage is refined through execution cases.',searchLabel:'Search prompts',searchInput:'Search by title or WCAG number',searchPlaceholder:'E.g. keyboard, text alternatives, 1.1.1',level:'Conformance level',search:'Search',promptCount:'entries',explanation:'Explanation and prompt',empty:'No matching prompts. Try another title or criterion number.',
 collectionLead:'Follow important topics from beginning to end. Articles and prompts evolve as standards and technology change.',collectionSummary:'Overview · criterion prompts · agent integration',nextTopics:'Upcoming topics',afterSelection:'Work begins after topic selection.',siteDescription:'Web accessibility education and practical resources for AI and business',jobTitle:'Web developer · technical educator and consultant'
};
const ja:Labels={
 seriesNavigation:'シリーズの学習ナビゲーション',currentChapter:'現在の記事',
 createdDate:'初版公開日',notPublished:'公開予定',modifiedDate:'最終更新日',
 preparationTitle:'この記事は準備中です。',preparationMessage:'執筆とレビュー後に、同じURLへ本文を追加します。全体の学習順序で今後のテーマをご確認ください。',preparationPrompt:'評価プロンプトもこの記事で提供する予定です。',sourceStandard:'基準の原文を読む',series:'シリーズ',prompts:'プロンプト',tools:'ツール',about:'紹介',resources:'資料',home:'ホーム',skip:'本文へスキップ',menu:'メインメニュー',archive:'アーカイブ',updates:'更新履歴',privacy:'個人情報について',inbox:'ローカル受信箱',language:'言語を選択',korean:'韓国語',review:'ローカル編集プレビュー',reviewNote:'新シリーズの記事とプロンプトは公開前の下書きです。',
 seriesTitle:'ウェブアクセシビリティ',seriesDescription:'WCAG 2.2の有効な達成基準ごとの解説、マルチモーダル評価プロンプトとエージェントへの応用。',seriesLead:'誰もが利用できるウェブを作るための基準。各項目を深く理解し、AIで評価する方法を学びます。',guide:'学習ガイド',drafts:'本の記事',overviewFlow:'概要 → 基準別の解説・プロンプト → 統合',start:'概要から読む',preparing:'公開準備中',getPrompts:'全プロンプトを受け取る',curriculum:'学習の順序',levelFilter:'適合レベルの絞り込み',all:'すべて',public:'公開済み',draft:'下書き',planned:'準備中',read:'読む',
 groups:['はじめに','知覚可能なウェブ','操作可能なウェブ','理解可能なウェブ','堅牢なウェブ','サービスへの接続'],captions:['まず視点と評価方法を学びます。','情報を見て、聞いて、別の形でも理解する。','キーボード、ポインター、時間、移動の障壁を減らす。','予測可能な動作、入力、認証の流れ。','支援技術と名前・役割・状態を共有する。','基準別評価をエージェントと運用に統合します。'],
 bundleHeading:'全プロンプトと実行順序が必要な方へ。',bundleAction:'資料集を受け取る',bundleArticleTitle:'このプロンプトを評価全体の流れにつなげましょう。',bundleArticleText:'シリーズの全プロンプトと入力資料の準備方法を資料集で提供します。',koreanResourceNotice:'資料の申請ページは現在韓国語です。全シリーズの公開承認後に資料集を提供します。',
 allChapters:'全体の学習順序',version:'バージョン',draftDate:'2026-10-01 下書き',toc:'この記事で学ぶこと',tocLabel:'記事の目次',evaluationPrompt:'評価プロンプト',authorNote:'ウェブの基準を実務の判断につなげます。',editorialDraft:'編集用下書き',pagination:'シリーズ内の移動',previous:'前の記事',next:'次の記事',
 promptTitle:'この項目の評価プロンプト',copy:'プロンプトをコピー',copied:'コピー済み',copySuccess:'プロンプトをコピーしました。',copyFailure:'自動コピーに失敗しました。以下のテキストを選択してコピーしてください。',promptHelp:'必要な資料を添えて実行してください。',promptFull:'評価プロンプト全文',
 libraryTitle:'アクセシビリティ評価プロンプト',libraryDescription:'WCAG基準別のマルチモーダル評価プロンプト。入力の準備と結果の解釈を解説します。',libraryLead:'各プロンプトに解説、入力資料、結果の読み方を添えています。実行事例を通じて評価範囲を検証していきます。',searchLabel:'プロンプトを検索',searchInput:'タイトルまたはWCAG番号で検索',searchPlaceholder:'例：キーボード、代替テキスト、1.1.1',level:'適合レベル',search:'検索',promptCount:'件の項目',explanation:'解説とプロンプト',empty:'該当するプロンプトはありません。別のタイトルや基準番号で検索してください。',
 collectionLead:'重要なテーマを最初から最後までつなげます。基準や技術の変化に合わせて、記事とプロンプトも更新します。',collectionSummary:'概要 · 基準別プロンプト · エージェント統合',nextTopics:'次のテーマ',afterSelection:'テーマの選定後に開始します。',siteDescription:'AIとビジネスのためのウェブアクセシビリティ教育と実務資料',jobTitle:'ウェブ開発者 · 技術教育・コンサルティング'
};
const zh:Labels={
 seriesNavigation:'系列学习导航',currentChapter:'当前文章',
 createdDate:'首次发布日期',notPublished:'尚未发布',modifiedDate:'最后更新日期',
 preparationTitle:'本文正在准备中。',preparationMessage:'编写与审核完成后，正文将添加至同一地址。您可以在完整学习顺序中查看即将介绍的主题。',preparationPrompt:'评估提示词也将在本文中提供。',sourceStandard:'阅读标准原文',series:'系列',prompts:'提示词',tools:'工具',about:'关于',resources:'资料',home:'首页',skip:'跳转到正文',menu:'主导航',archive:'归档',updates:'更新记录',privacy:'隐私说明',inbox:'本地收件箱',language:'选择语言',korean:'韩语',review:'本地编辑预览',reviewNote:'新系列的文章与提示词均为尚未发布的草稿。',
 seriesTitle:'Web 无障碍',seriesDescription:'逐项解读 WCAG 2.2 的所有有效成功标准，提供多模态评估提示词与智能体应用方法。',seriesLead:'让每个人都能使用 Web 的标准。深入理解每项要求，学习如何借助 AI 进行评估。',guide:'学习指南',drafts:'篇学习内容',overviewFlow:'概述 → 标准解读与提示词 → 整合',start:'从概述开始阅读',preparing:'准备发布',getPrompts:'获取全部提示词',curriculum:'学习顺序',levelFilter:'符合性等级筛选',all:'全部',public:'已发布',draft:'草稿',planned:'准备中',read:'阅读',
 groups:['入门','可感知的 Web','可操作的 Web','可理解的 Web','稳健的 Web','连接到服务'],captions:['先了解评估视角与方法。','通过视觉、听觉及其他形式获取信息。','减少键盘、指针、时间与导航方面的障碍。','可预测的行为、输入和身份验证流程。','向辅助技术传达名称、角色与状态。','将标准评估整合到智能体与运维流程中。'],
 bundleHeading:'需要全部提示词与执行顺序？',bundleAction:'获取资料集',bundleArticleTitle:'将此提示词接入完整的评估流程。',bundleArticleText:'资料集包含系列提示词与证据准备方法。',koreanResourceNotice:'资料申请页面目前为韩语。完整系列通过发布审核后，将提供资料集。',
 allChapters:'完整学习顺序',version:'版本',draftDate:'2026-10-01 草稿',toc:'本文学习内容',tocLabel:'文章目录',evaluationPrompt:'评估提示词',authorNote:'将 Web 标准转化为实践中的判断。',editorialDraft:'编辑草稿',pagination:'系列导航',previous:'上一篇',next:'下一篇',
 promptTitle:'本项评估提示词',copy:'复制提示词',copied:'已复制',copySuccess:'提示词已复制。',copyFailure:'自动复制失败，请选择并复制下方文本。',promptHelp:'请提供所需资料后再运行提示词。',promptFull:'完整评估提示词',
 libraryTitle:'无障碍评估提示词',libraryDescription:'按 WCAG 标准查找多模态无障碍评估提示词，并了解输入准备与结果解读。',libraryLead:'每个提示词都附有解读、所需资料与结果分析方法。评估范围将通过执行案例持续验证。',searchLabel:'搜索提示词',searchInput:'按标题或 WCAG 编号搜索',searchPlaceholder:'例如：键盘、替代文本、1.1.1',level:'符合性等级',search:'搜索',promptCount:'个条目',explanation:'解读与提示词',empty:'没有匹配的提示词，请尝试其他标题或标准编号。',
 collectionLead:'从头到尾系统学习重要主题。随着标准与技术发展，文章和提示词也将持续更新。',collectionSummary:'概述 · 标准提示词 · 智能体整合',nextTopics:'后续主题',afterSelection:'选定主题后开始。',siteDescription:'面向 AI 与业务的 Web 无障碍教育和实践资料',jobTitle:'Web 开发者 · 技术教育与咨询'
};
export const labels:Record<Language,Labels>={ko,en,ja,zh};
export function languageLinks(path:string,current:Language){return (Object.keys(languages) as Language[]).map(lang=>({lang,name:languages[lang],path:localizedPath(path,lang),current:lang===current}));}
