import { bundle,bundleReady,isPreview,loopback,SERIES_VERSION } from './content';
export const VERSION=SERIES_VERSION;const CONSENT_VERSION='2026-10-01';
export const hash=async(text:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
export function validateLead(form:FormData){const email=String(form.get('email')??'').trim().toLowerCase();const role=String(form.get('role')??'').trim();const updates=form.get('updates')==='yes';if(String(form.get('company_url')??''))return{error:'신청을 처리하지 못했습니다. 다시 시도해주세요.'};if(email.length>254||! /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email))return{error:'받으실 이메일 주소를 확인해주세요.'};if(!['','developer','designer','business','other'].includes(role))return{error:'역할을 목록에서 선택해주세요.'};if(form.get('privacy')!=='yes')return{error:'자료 전달을 위한 개인정보 안내를 확인해주세요.'};return{email,role,updates};}
export async function submitLead(form:FormData,url:URL,env:App.Platform['env'],ip:string){const input=validateLead(form);if(input.error)return{ok:false,error:input.error};const preview=isPreview(url);if(!preview&&!bundleReady())return{ok:false,error:'전체 자료를 편집하고 있습니다. 공개가 완료되면 신청하실 수 있습니다.'};if(!env.LEADS_DB)return{ok:false,error:'자료 신청을 준비 중입니다. 잠시 후 다시 방문해주세요.'};if(!['capture','cloudflare'].includes(env.MAIL_MODE??''))return{ok:false,error:'자료 전달을 준비 중입니다. 잠시 후 다시 방문해주세요.'};if(env.MAIL_MODE==='capture'&&!loopback(url))return{ok:false,error:'자료 전달을 준비 중입니다.'};
const db=env.LEADS_DB,now=new Date().toISOString(),hour=Math.floor(Date.now()/3600000);const limitKey=await hash(ip+':'+hour);await db.prepare('INSERT INTO request_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').bind(limitKey,Date.now()+3600000).run();const usage=await db.prepare('SELECT count FROM request_limits WHERE key=?').bind(limitKey).first<{count:number}>();if((usage?.count??0)>5)return{ok:false,error:'신청 횟수가 많습니다. 한 시간 후 다시 시도해주세요.'};
const leadId=crypto.randomUUID(),requestId=crypto.randomUUID(),downloadToken=token(),unsubscribeToken=token(),downloadHash=await hash(downloadToken),unsubscribeHash=await hash(unsubscribeToken);const origin=loopback(url)?url.origin:env.SITE_URL;if(!origin||!/^https:\/\//.test(origin)&&!loopback(url))return{ok:false,error:'자료 전달 설정을 확인하고 있습니다.'};
await db.prepare('INSERT INTO leads(id,email,role,unsubscribe_hash,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET role=CASE WHEN excluded.role<>\'\' THEN excluded.role ELSE leads.role END,updated_at=excluded.updated_at').bind(leadId,input.email,input.role,unsubscribeHash,now,now).run();const lead=await db.prepare('SELECT id FROM leads WHERE email=?').bind(input.email).first<{id:string}>();if(!lead)throw new Error('LEAD_SAVE_FAILED');
const existing=await db.prepare('SELECT id,status,expires_at FROM material_requests WHERE lead_id=? AND series=? AND version=?').bind(lead.id,'accessibility',VERSION).first<{id:string;status:string;expires_at:number}>();if(existing&&existing.expires_at<Date.now()){await db.prepare('DELETE FROM material_requests WHERE id=? AND expires_at<?').bind(existing.id,Date.now()).run();}else if(existing){if(existing.status==='failed'&&env.MAIL_MODE==='capture'&&loopback(url))return deliver(existing.id,url,env,preview);return{ok:true,captured:existing.status==='captured',duplicate:true,pending:['pending','sending','failed'].includes(existing.status),message:existing.status==='failed'?'신청은 저장되어 있지만 발송 확인이 필요합니다. me@jangwook.net으로 문의해주세요.':'이미 신청하신 자료입니다. 메일함을 확인해주세요.'};}
// Explicit confirmation POST activates requested subscriptions. Repeated requests never revoke or silently replace consent.
const link=origin+'/confirm/'+downloadToken;const stop=origin+'/unsubscribe/'+unsubscribeToken;const subject='[jangwook.net] 웹 접근성 전체 프롬프트 · v'+VERSION;const body='안녕하세요. 김장욱입니다.\n\n신청하신 웹 접근성 시리즈 전체 프롬프트와 실행 순서를 전달합니다.\n\n모음집 받기: '+link+'\n링크 유효 기간: 7일\n자료 버전: '+VERSION+'\n'+(preview?'로컬 편집 초안이며 실제 모델 평가를 완료한 자료는 아닙니다.\n':'')+'\n업데이트 구독을 선택하셨다면 위 링크로 이메일을 확인한 이후 적용됩니다.\n업데이트 수신 설정: '+stop+'\n\n기준 해설: https://jangwook.net/series/accessibility';
await db.batch([db.prepare('INSERT INTO management_tokens(token_hash,lead_id,created_at) VALUES(?,?,?)').bind(unsubscribeHash,lead.id,now),db.prepare('INSERT INTO lead_consents(lead_id,scope,granted,version,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(lead_id,scope) DO UPDATE SET granted=excluded.granted,version=excluded.version,updated_at=excluded.updated_at,confirmed_at=NULL').bind(lead.id,'accessibility-updates',input.updates?1:0,CONSENT_VERSION,now),db.prepare('INSERT INTO consent_events(id,lead_id,scope,granted,version,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),lead.id,'accessibility-updates',input.updates?1:0,CONSENT_VERSION,now),db.prepare('INSERT OR IGNORE INTO material_requests(id,lead_id,series,version,token_hash,expires_at,status,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(requestId,lead.id,'accessibility',VERSION,downloadHash,Date.now()+7*86400000,'pending',now),db.prepare('INSERT INTO mail_outbox(id,request_id,subject,body,status,updated_at) SELECT ?,id,?,?,?,? FROM material_requests WHERE id=?').bind(crypto.randomUUID(),subject,body,'pending',now,requestId)]);
// Only the winning request can claim the outbox; this is also the retry entry point.
const finalRequest=await db.prepare('SELECT id FROM material_requests WHERE lead_id=? AND series=? AND version=?').bind(lead.id,'accessibility',VERSION).first<{id:string}>();return deliver(finalRequest?.id??requestId,url,env,preview);}
export async function deliver(requestId:string,url:URL,env:App.Platform['env'],preview=false){const db=env.LEADS_DB;const claim=await db.prepare("UPDATE mail_outbox SET status='sending',attempts=attempts+1,updated_at=? WHERE request_id=? AND status IN ('pending','failed') RETURNING subject,body").bind(new Date().toISOString(),requestId).first<{subject:string;body:string}>();if(!claim)return{ok:true,pending:true,message:'자료 신청을 접수했습니다.'};await db.prepare("UPDATE material_requests SET status='sending' WHERE id=?").bind(requestId).run();let providerId:string|undefined;try{if(env.MAIL_MODE==='capture'&&loopback(url)){providerId='local-capture';}else if(env.MAIL_MODE==='cloudflare'&&env.EMAIL&&env.FROM_EMAIL&&!preview){const recipient=await db.prepare('SELECT email FROM leads JOIN material_requests ON leads.id=material_requests.lead_id WHERE material_requests.id=?').bind(requestId).first<{email:string}>();if(!recipient)throw new Error('RECIPIENT_MISSING');const bytes=new TextEncoder().encode(bundle(false));let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const receipt=await env.EMAIL.send({from:env.FROM_EMAIL,to:recipient.email,subject:claim.subject,text:claim.body,attachments:[{filename:'web-accessibility-prompts-v'+VERSION+'.md',content:btoa(binary),type:'text/markdown',disposition:'attachment'}]});if(!receipt.messageId)throw new Error('PROVIDER_RECEIPT_MISSING');providerId=receipt.messageId;}else throw new Error('MAIL_CONFIGURATION_UNAVAILABLE');const status=providerId==='local-capture'?'captured':'accepted';await db.batch([db.prepare('UPDATE mail_outbox SET status=?,provider_id=?,error_code=NULL,updated_at=? WHERE request_id=?').bind(status,providerId,new Date().toISOString(),requestId),db.prepare('UPDATE material_requests SET status=? WHERE id=?').bind(status,requestId)]);return{ok:true,captured:status==='captured',message:status==='captured'?'로컬 신청과 메일 생성이 완료되었습니다. 개발용 메일함에서 자료 링크를 확인하세요.':'자료 신청을 접수하고 메일 서비스에 전달했습니다. 메일함을 확인해주세요.'};}catch{if(providerId&&providerId!=='local-capture'){try{await db.prepare("UPDATE mail_outbox SET provider_id=?,error_code='ACCEPTANCE_RECORD_UNCONFIRMED',updated_at=? WHERE request_id=?").bind(providerId,new Date().toISOString(),requestId).run();}catch{/* Keep the sending claim: a known provider receipt must never trigger an automatic retry. */}return{ok:true,pending:true,message:'메일 서비스에 전달했습니다. 발송 기록을 확인하고 있습니다.'};}await db.batch([db.prepare("UPDATE mail_outbox SET status='failed',error_code='SEND_FAILED',updated_at=? WHERE request_id=?").bind(new Date().toISOString(),requestId),db.prepare("UPDATE material_requests SET status='failed' WHERE id=?").bind(requestId)]);return{ok:true,pending:true,message:'신청은 저장되었습니다. 메일 전송이 지연되고 있어 다시 처리해야 합니다.'};}}
