import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {createRequire} from 'node:module';
const root=process.argv[2],base=process.argv[3],out=process.argv[4];const require=createRequire(root+'/package.json');const {chromium,webkit}=require('playwright');const axe=fs.readFileSync(require.resolve('axe-core/axe.min.js'),'utf8');
const catalog=JSON.parse(fs.readFileSync(root+'/src/lib/content/catalog.json'));const trans=JSON.parse(fs.readFileSync(root+'/src/lib/content/translations.json'));const langs=['ko','en','ja','zh'],slug='audio-only-and-video-only-prerecorded';const loc=(lang,p)=>lang==='ko'?p:'/'+lang+p;const report=process.env.MEDIA_ONLY?JSON.parse(fs.readFileSync(out)):{base,scope:'SSR publication identity, source evidence preservation, localized figures, responsive/no-JS and native Chromium/WebKit playback. Not WCAG certification or native LLM video evaluation.',article:[],oldArticles:[],assets:[],browser:[],playback:[],noJS:[],errors:[]};
report.errors=[];report.playback=[];const b=await chromium.launch();try{
if(!process.env.MEDIA_ONLY){
const c=await b.newContext();
for(const lang of langs){
 const posts=lang==='ko'?catalog:trans[lang],p=posts.find(p=>p.slug===slug),path=loc(lang,'/series/accessibility/'+slug);assert.equal(p.status,'published');assert.equal(p.approvalHash,p.sourceHash);
 const r=await c.request.get(base+path);assert.equal(r.status(),200);const h=await r.text();assert.ok(h.includes('article-source-sha256" content="'+p.sourceHash));assert.ok(h.includes('<html lang="'+lang+'"'));assert.ok(!h.includes('content="noindex'));assert.ok(h.includes('BlogPosting'));assert.ok(h.includes('CreativeWorkSeries'));assert.ok(h.includes('data-source-sha256="'+p.sourceHash));assert.ok(h.includes('inventory_complete_within_scope'));assert.ok(h.includes('<iframe'));assert.ok(h.includes('teaching/'+lang+'.mp4'));assert.ok(!h.includes('tts-probe'));
 const dates=[p.firstPublishedAt,p.updatedAt];for(const d of dates)assert.ok(h.includes(d));for(const l of langs)assert.ok(h.includes('hreflang="'+l+'"'));report.article.push({lang,path,sourceHash:p.sourceHash,SSR:true,dates,public:true});
 for(const old of posts.filter(x=>['overview','non-text-content'].includes(x.slug))){const r=await c.request.get(base+loc(lang,'/series/accessibility/'+old.slug));assert.equal(r.status(),200);assert.ok((await r.text()).includes('article-source-sha256" content="'+old.sourceHash));report.oldArticles.push({lang,slug:old.slug,hashMatch:true,firstPublishedAt:old.firstPublishedAt});}
 for(const asset of [...new Set([...p.body.matchAll(/src="([^" ]+\.svg)"/g)].map(m=>m[1])), '/lab-fixtures/media-1.2.1/teaching/'+lang+'.mp4','/lab-fixtures/media-1.2.1/teaching/'+lang+'.jpg']){const r=await c.request.get(base+asset);assert.equal(r.status(),200,asset);assert.equal(crypto.createHash('sha256').update(await r.body()).digest('hex'),crypto.createHash('sha256').update(fs.readFileSync(root+'/static'+asset)).digest('hex'));report.assets.push({path:asset,hashMatch:true});}
 const home=await c.request.get(base+(lang==='ko'?'/ko/':'/'+lang+'/'));assert.ok((await home.text()).includes(loc(lang,'/series/accessibility/'+slug)));const updates=await c.request.get(base+loc(lang,'/updates'));assert.equal(updates.status(),200);const xml=await c.request.get(base+'/sitemap.xml');assert.ok((await xml.text()).includes('https://jangwook.net'+path));
 for(const width of [1440,390,320]){const ctx=await b.newContext({viewport:{width,height:1100}});await ctx.route(/scriptwrapper|mediavine|doubleclick|googlesyndication|ezoic/,r=>r.abort());const page=await ctx.newPage();await page.goto(base+path,{waitUntil:'networkidle'});assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.learning-figure').count(),4);await page.locator('.learning-figure').nth(2).locator('img').scrollIntoViewIfNeeded();assert.ok(await page.locator('.learning-figure img').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0)));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.addScriptTag({content:axe});const a=await page.evaluate(async()=>await window.axe.run({include:[['main']],exclude:[['iframe']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));assert.deepEqual(a.violations.map(v=>v.id),[]);if(width===320){await page.addStyleTag({content:'html{font-size:200%}'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}if(width===390)await page.screenshot({path:out.replace('.json','-'+lang+'-390.png'),fullPage:true});report.browser.push({lang,width,figures:4,overflow:false,axeViolations:[]});await ctx.close();}
 const ctx=await b.newContext({javaScriptEnabled:false});const page=await ctx.newPage();await page.goto(base+path);assert.ok((await page.locator('.prose').innerText()).length>5000);assert.equal(await page.locator('.language-nav a').count(),4);assert.equal(await page.locator('video').count(),1);report.noJS.push({lang,readable:true,videoControlsPresent:true});await ctx.close();
}
const prov=JSON.parse(fs.readFileSync(root+'/static/lab-fixtures/media-1.2.1/provenance.json'));for(const f of prov.original_files){const r=await c.request.get(base+f.path);assert.equal(r.status(),200);assert.equal(crypto.createHash('sha256').update(await r.body()).digest('hex'),f.sha256);report.assets.push({path:f.path,originalHashMatch:true});}
for(const f of ['/lab-fixtures/media-1.2.1/original/snapshot.json','/lab-fixtures/media-1.2.1/original/cases/K63/snapshot.json'])assert.equal((await c.request.get(base+f)).status(),404);
await c.close();
}
for(const [engineName,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch();try{for(const lang of langs){const ctx=await browser.newContext({viewport:{width:1280,height:1000}});await ctx.route(/scriptwrapper|mediavine|doubleclick|googlesyndication|ezoic/,r=>r.abort());const page=await ctx.newPage();await page.goto(base+loc(lang,'/series/accessibility/'+slug));const v=page.locator('.teaching-video video');await v.scrollIntoViewIfNeeded();await v.focus();if(engineName==='chromium')await v.press('Space');else{const box=await v.boundingBox();await v.click({position:{x:35,y:box.height-16}});}await page.waitForTimeout(1100);const d=await v.evaluate(v=>({paused:v.paused,currentTime:v.currentTime,duration:v.duration,error:v.error?.code??null,width:v.videoWidth}));assert.equal(d.paused,false);assert.ok(d.currentTime>0&&Math.abs(d.duration-30)<.1&&d.width===1280);assert.equal(d.error,null);await v.evaluate(async v=>{v.pause();const done=new Promise((resolve,reject)=>{v.addEventListener("seeked",resolve,{once:true});setTimeout(()=>reject(new Error("seek timeout")),10000);});v.currentTime=26;await done;});assert.ok(await v.evaluate(v=>v.currentTime>=25.8));report.playback.push({engine:engineName,lang,kind:'Hyperframes teaching video',nativeControl:engineName==='chromium'?'focused Space':'native play click',seekToFinalScreen:true,...d});
 const frame=page.frameLocator('iframe[sandbox]').first();await page.locator('iframe[sandbox]').first().scrollIntoViewIfNeeded();const old=frame.locator('video');await old.scrollIntoViewIfNeeded();if(engineName==='chromium'){await old.focus();await old.press('Space');}else{const box=await old.boundingBox();await old.click({position:{x:35,y:box.height-16}});}for(let i=0;i<100&&await old.evaluate(v=>v.paused||v.currentTime<=0);i++)await page.waitForTimeout(100);const q=await old.evaluate(v=>({paused:v.paused,currentTime:v.currentTime,duration:v.duration,error:v.error?.code??null}));assert.equal(q.paused,false);assert.ok(q.currentTime>0&&Math.abs(q.duration-19.916667)<.1);assert.equal(q.error,null);report.playback.push({engine:engineName,lang,kind:'original-video browser encoding',...q});await ctx.close();}}finally{await browser.close();}
}
}catch(e){report.errors.push(String(e));throw e;}finally{await b.close();fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({base,articles:report.article.length,oldArticles:report.oldArticles.length,assets:report.assets.length,browser:report.browser.length,noJS:report.noJS.length,nativePlayback:report.playback.length,errors:report.errors}));}
