import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {getPlatformProxy} from 'wrangler';
const base='http://127.0.0.1:8787';
const report={checks:[],errors:[]};
const matrix=[['/',302],['/series',200],['/series/accessibility',200],['/services',200],['/series/accessibility/overview',200],['/series/accessibility/non-text-content',200],['/en/series/accessibility/overview',200],['/ja/series/accessibility/non-text-content',200],['/zh/series/accessibility/non-text-content',200],['/dev/inbox',404],['/ko/blog/legacy-article',404],['/en/blog/legacy-article',404],['/archive',200],['/ko/blog/ko/salon-chatgpt-static-hosting-web-development/',200],['/ko/',200],['/en/',200],['/ja/',200],['/zh/',200],['/ko/about',308],['/_worker.js',404],['/downloads/invalid',404],['/confirm/invalid',404]];
for(const [path,status] of matrix){const r=await fetch(base+path,{redirect:'manual'});report.checks.push({path,status:r.status});if(r.status!==status)report.errors.push(path+' expected '+status);}
for(const path of ['/sitemap.xml','/rss.xml','/en/rss.xml','/ja/rss.xml','/zh/rss.xml']){const r=await fetch(base+path);const body=await r.text();if(r.status!==200||body.includes('/keyboard')||!body.includes('/overview')||!body.includes('/non-text-content'))report.errors.push('Draft feed leak '+path);report.checks.push({path,status:r.status,draftsExcluded:true});}
for(const lang of ['ko','en','ja','zh']){const prefix=lang==='ko'?'':'/'+lang;for(const slug of ['overview','non-text-content','keyboard']){const r=await fetch(base+prefix+'/series/accessibility/'+slug);const text=await r.text();if(slug!=='keyboard'){if(r.headers.get('x-robots-tag')?.includes('noindex')||!text.includes('class="prompt-panel"')||!text.includes('class="prose"'))report.errors.push('Published chapter missing '+lang);continue;}if(!r.headers.get('x-robots-tag')?.includes('noindex')||text.includes('class="prompt-panel"')||text.includes('class="prose"'))report.errors.push('Preparing page content leak '+lang+'/'+slug);}}
const resource=await fetch(base+'/resources/accessibility',{redirect:'manual'});assert.equal(resource.status,308);assert.ok(resource.headers.get('location').endsWith('/series/accessibility/agentic-accessibility'));report.checks.push({path:'/resources/accessibility',formRemoved:true,redirect:resource.headers.get('location')});
const ads=await fetch(base+'/ads.txt',{redirect:'manual'});const adsBody=await ads.text();assert.equal(ads.status,200);assert.match(ads.headers.get('content-type')??'',/^text\/plain/);assert.equal(adsBody,await fs.readFile('static/ads.txt','utf8'));report.checks.push({path:'/ads.txt',status:ads.status,contentType:ads.headers.get('content-type'),matchesJourneySource:true});
const proxy=await getPlatformProxy({configPath:'wrangler.jsonc'});const db=proxy.env.LEADS_DB;const id='qa-retention-'+crypto.randomUUID();const bucket='qa-retention-'+crypto.randomUUID();
try{await db.prepare('INSERT INTO leads(id,email,unsubscribe_hash,created_at,updated_at) VALUES(?,?,?,?,?)').bind(id,id+'@example.test',crypto.randomUUID(),'2020-01-01T00:00:00Z','2020-01-01T00:00:00Z').run();await db.prepare('INSERT INTO request_limits(key,count,expires_at) VALUES(?,1,?)').bind(bucket,Date.now()-1000).run();const response=await fetch(base+'/__scheduled?cron='+encodeURIComponent('17 18 * * *'));assert.equal(response.status,200);const deadline=Date.now()+5000;while(await db.prepare('SELECT id FROM leads WHERE id=?').bind(id).first()){if(Date.now()>deadline)throw new Error('Retention handler did not complete');await new Promise(resolve=>setTimeout(resolve,50));}assert.equal(await db.prepare('SELECT id FROM leads WHERE id=?').bind(id).first(),null);assert.equal(await db.prepare('SELECT key FROM request_limits WHERE key=?').bind(bucket).first(),null);report.checks.push({scheduledRetention:true,expiredRateBucket:true});}catch(e){report.errors.push(String(e));}finally{await db.prepare('DELETE FROM leads WHERE id=?').bind(id).run();await db.prepare('DELETE FROM request_limits WHERE key=?').bind(bucket).run();await proxy.dispose();}
await fs.writeFile('reports/worker-validation.json',JSON.stringify(report,null,2));console.log(report);if(report.errors.length)process.exit(1);
