import fs from 'node:fs/promises';import {chromium} from 'playwright';import {getPlatformProxy} from 'wrangler';
const base=process.env.TEST_BASE_URL??'http://127.0.0.1:5173';await fs.mkdir('reports/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true});const axe=await fs.readFile('node_modules/axe-core/axe.min.js','utf8');const report={pages:[],flows:[],errors:[]};
const paths=['/','/series','/series/accessibility','/series/accessibility/overview','/series/accessibility/non-text-content','/prompts','/services','/about','/privacy','/archive','/ko/blog/ko/salon-chatgpt-static-hosting-web-development/','/en/blog/en/tauri-pixijs-ios-game-development/','/ja/blog/ja/ssr-survey-analysis/','/zh/blog/zh/ssr-survey-analysis/'];
for(const width of [1440,390,320]){const page=await browser.newPage({locale:'ko-KR',viewport:{width,height:1000},reducedMotion:'reduce'});page.on('pageerror',e=>report.errors.push(e.message));for(const path of paths){const response=await page.goto(base+path);await page.evaluate(()=>document.fonts.ready);await page.addScriptTag({content:axe});const result=await page.evaluate(async()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,h1:document.querySelectorAll('h1').length,violations:(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))}));report.pages.push({path,width,status:response.status(),...result});if(result.width>width||result.h1!==1||result.violations.length)report.errors.push('Page check '+width+' '+path);if(['/', '/series/accessibility','/series/accessibility/non-text-content'].includes(path))await page.screenshot({path:'reports/screenshots/'+(path==='/'?'home':path.split('/').at(-1))+'-'+width+'.png',fullPage:path==='/'});}await page.close();}
const page=await browser.newPage({locale:'ko-KR',viewport:{width:1280,height:950},reducedMotion:'reduce'});await page.goto(base+'/');await page.keyboard.press('Tab');if(await page.locator(':focus').innerText()!=='본문으로 건너뛰기')report.errors.push('Skip link not first');await page.keyboard.press('Enter');if(await page.locator(':focus').getAttribute('id')!=='main')report.errors.push('Skip destination');report.flows.push('keyboard skip link');await page.goto(base+'/prompts');await page.locator('#prompt-search').fill('3.3.8');await page.waitForTimeout(150);if(await page.locator('.prompt-card').count()!==1)report.errors.push('Prompt search');report.flows.push('prompt search');await page.goto(base+'/series/accessibility');await page.getByRole('button',{name:'AAA',exact:true}).click();if(await page.locator('.chapter-group li').count()!==33)report.errors.push('AAA filter');report.flows.push('level filter');
for(const path of ['/','/series/accessibility/non-text-content']){await page.goto(base+path);await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await page.evaluate(()=>document.fonts.ready);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)report.errors.push('200% text resize '+path);}
report.flows.push('200% text resize');await page.goto(base+'/ko/blog/ko/ssr-survey-analysis/');await page.getByRole('button',{name:'다이어그램 보기',exact:true}).first().click();await page.waitForFunction(()=>document.querySelector('.archive-diagram:not([hidden]) svg'));await page.addScriptTag({content:axe});const diagramViolations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>v.id));if(diagramViolations.length)report.errors.push('Diagram accessibility '+diagramViolations.join(','));report.flows.push('on-demand original Mermaid diagram');await page.close();
const context=await browser.newContext({javaScriptEnabled:false,reducedMotion:'reduce',viewport:{width:390,height:900}});const nojs=await context.newPage();await nojs.goto(base+'/series/accessibility/overview');if(await nojs.locator('.prose').count()!==1||await nojs.locator('.learning-figure').count()!==4)report.errors.push('No JS article');report.flows.push('no-JS published article');await context.close();await browser.close();await fs.writeFile('reports/browser-validation.json',JSON.stringify(report,null,2));console.log({pages:report.pages.length,flows:report.flows,errors:report.errors});if(report.errors.length)process.exit(1);
