// Generated by the SvelteKit Cloudflare adapter; this wrapper stays hand-edited.
// @ts-ignore generated build entry is created by npm run build
import application from '../.svelte-kit/cloudflare/_worker.js';
import {isMediaAsset,serveMedia} from './media-assets';
export default {
  async fetch(request: Request, env: App.Platform['env'], ctx: ExecutionContext) {
    if (env.ASSETS && isMediaAsset(new URL(request.url).pathname)) return serveMedia(request, env.ASSETS);
    return application.fetch(request, env, ctx);
  },
  async scheduled(_event: ScheduledController, env: App.Platform['env'], ctx: ExecutionContext) {
    ctx.waitUntil((async()=>{
      const cutoff=new Date();
      cutoff.setUTCMonth(cutoff.getUTCMonth()-12);
      await env.LEADS_DB.batch([
        env.LEADS_DB.prepare('DELETE FROM leads WHERE updated_at<?').bind(cutoff.toISOString()),
        env.LEADS_DB.prepare('DELETE FROM request_limits WHERE expires_at<?').bind(Date.now())
      ]);
    })());
  }
};
