<script lang="ts">
import Arrow from './Arrow.svelte';import {localizedPath} from '$lib/series/i18n';import type {loadHome} from '$lib/server/home';
let {data}:{data:ReturnType<typeof loadHome>}=$props();let ui=$derived(data.ui);let home=$derived(data.home);
</script>
<svelte:head><title>{data.seo.title}</title><meta name="description" content={home.description}/><link rel="alternate" hreflang="x-default" href="https://jangwook.net/"/></svelte:head>
<div class="wrap quiet-home" lang={data.lang}>
<section aria-labelledby="latest-title"><p class="eyebrow">Web for AI / Business / Everyone</p><h1 id="latest-title">{home.reading}</h1>{#if data.sample.length}<ol class="latest-articles">{#each data.sample as p}<li><a href={localizedPath('/series/accessibility/'+p.slug,data.lang)}><div><p class="eyebrow">{ui.seriesTitle} · <time datetime={p.firstPublishedAt!}>{new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(p.firstPublishedAt!))}</time></p><h2>{p.title}</h2><p class="latest-summary">{p.summary}</p></div><Arrow size={20}/></a></li>{/each}</ol>{:else}<p class="empty-state">{home.empty}</p>{/if}</section>
<section class="home-link-section" aria-labelledby="series-title"><h2 id="series-title">{ui.series}</h2><a class="home-series-link" href={localizedPath('/series/accessibility',data.lang)}><span>{ui.seriesTitle}<small>WCAG 2.2 · {data.chapters} {ui.drafts}</small></span><Arrow size={20}/></a><a class="text-link" href={localizedPath('/series',data.lang)}>{home.allSeries}<Arrow size={16}/></a></section>
<nav class="home-link-section home-menu-links" aria-label={home.browse}><h2>{home.browse}</h2><a href={localizedPath('/prompts',data.lang)}>{ui.prompts}<Arrow size={16}/></a><a href={localizedPath('/about',data.lang)}>{ui.about}<Arrow size={16}/></a><a href={localizedPath('/archive',data.lang)}>{ui.archive}<Arrow size={16}/></a><a href={localizedPath('/updates',data.lang)}>{ui.updates}<Arrow size={16}/></a><a href={localizedPath('/services',data.lang)}>{data.lang==='ko'?'서비스':data.lang==='en'?'Services':data.lang==='ja'?'サービス':'服务'}<Arrow size={16}/></a><a href={localizedPath('/labs/accessibility/media-alternatives',data.lang)}>{data.lang==='ko'?'실습 페이지':data.lang==='en'?'Practice pages':data.lang==='ja'?'実習ページ':'练习页面'}<Arrow size={16}/></a><a href={localizedPath('/privacy',data.lang)}>{ui.privacy}<Arrow size={16}/></a></nav>
</div>
