<script lang="ts">
import MediaTeachingVideo from './MediaTeachingVideo.svelte';
import {localizedPath} from '$lib/series/i18n';import type {loadMediaLab} from '$lib/server/labs';
let {data}:{data:ReturnType<typeof loadMediaLab>}=$props();
</script>
<svelte:head><title>{data.seo.title}</title><meta name="description" content={data.ui.lead}/><link rel="alternate" hreflang="x-default" href={data.seo.canonical.replace(/^https:\/\/jangwook\.net\/(en|ja|zh)/,'https://jangwook.net')}/></svelte:head>
<section class="wrap page-intro"><p class="eyebrow">WCAG 2.2 · SC 1.2.1</p><h1>{data.ui.title}</h1><p class="lead">{data.ui.lead}</p></section>
<div class="wrap section lab-layout"><nav aria-label={data.ui.all}><h2>{data.ui.all}</h2><ol>{#each data.cases as item}<li><a href={item.path} aria-current={item.id===data.selected.id?'page':undefined}><small>{item.id}</small>{item.name}</a></li>{/each}</ol></nav>
<section class="lab-selected" aria-labelledby="case-heading"><p class="eyebrow">{data.selected.id}</p><h2 id="case-heading">{data.selected.name}</h2><p>{data.selected.reason}</p><iframe src={data.frame} title={data.ui.frame+' — '+data.selected.name} loading="lazy" sandbox="allow-same-origin allow-scripts" referrerpolicy="no-referrer"></iframe><div class="lab-links"><a href={data.frame}>{data.ui.open}</a><a href={data.original}>{data.ui.original}</a></div><p class="lab-note">{data.ui.note}</p><a href={localizedPath('/series/accessibility/audio-only-and-video-only-prerecorded',data.lang)}>{data.ui.article}</a></section></div>
<div class="wrap section"><MediaTeachingVideo lang={data.lang}/></div><section class="wrap section prior-target"><details><summary>{data.ui.overviewHeading} · SC 1.1.1</summary><p>{data.ui.overviewNote}</p><a href={localizedPath('/series/accessibility/overview',data.lang)}>{data.ui.overviewOpen}</a><iframe src={localizedPath('/series/accessibility/overview',data.lang)} title={data.ui.overviewFrame} loading="lazy" sandbox="allow-same-origin" referrerpolicy="no-referrer"></iframe></details></section>
<style>.prior-target summary{cursor:pointer;font-weight:600;padding:16px 0}.prior-target details{border-top:1px solid var(--rule,#deded9)}.prior-target p{line-height:1.85}.lab-layout{display:grid;grid-template-columns:250px minmax(0,1fr);gap:56px}.lab-layout nav h2{font-size:16px}.lab-layout ol{padding:0;list-style:none;margin:20px 0}.lab-layout nav a{display:flex;gap:12px;padding:12px 4px;border-bottom:1px solid var(--rule,#deded9);text-decoration:none;font-size:14px}.lab-layout nav a[aria-current]{font-weight:700;border-left:3px solid var(--ink,#252525);padding-left:12px}.lab-layout small{flex:0 0 2.5em;white-space:nowrap;color:var(--muted,#62625e);font-variant-numeric:tabular-nums}.lab-selected{min-width:0}.lab-selected h2{margin-top:0}.lab-selected p{line-height:1.85}iframe{display:block;width:100%;height:700px;border:1px solid var(--rule,#deded9);border-radius:6px;background:#fafaf8;margin:24px 0 12px}.lab-links{display:flex;gap:24px;flex-wrap:wrap}.lab-links a{padding:12px 0}.lab-note{font-size:14px;color:var(--muted,#62625e);margin:24px 0;padding-top:24px;border-top:1px solid var(--rule,#deded9)}@media(max-width:760px){.lab-layout{grid-template-columns:1fr;gap:24px}.lab-layout nav ol{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 12px}.lab-layout nav a{height:100%;overflow-wrap:anywhere}iframe{height:620px}}</style>
