<script lang="ts">
import SeriesStructuredData from './SeriesStructuredData.svelte';
import Arrow from './Arrow.svelte';import {localizedPath} from '$lib/series/i18n';import type {loadCurriculum} from '$lib/server/series';
let {data}:{data:ReturnType<typeof loadCurriculum>}=$props();let filter=$state('all');let ui=$derived(data.ui);let groups=$derived(['intro','1','2','3','4','outro'].map((id,i)=>({id,name:ui.groups[i],caption:ui.captions[i]})));
</script>
<svelte:head><title>{ui.seriesTitle} — jangwook.net</title><meta name="description" content={ui.seriesDescription}/></svelte:head>
<SeriesStructuredData chapters={data.chapters} lang={data.lang}/><section class="wrap page-intro series-intro"><div><p class="eyebrow">SERIES 01 / WEB FOR EVERYONE</p><h1>{ui.seriesTitle}</h1><p class="lead">{ui.seriesLead}</p></div><aside class="series-guide"><p class="eyebrow">{ui.guide}</p><strong>{data.posts.length}<span>{ui.drafts}</span></strong><p>WCAG 2.2 A · AA · AAA<br/>{ui.overviewFlow}</p>{#if data.posts.find(p=>p.slug==='overview')?.available}<a class="button" href={localizedPath('/series/accessibility/overview',data.lang)}>{ui.start} <Arrow/></a>{:else}<span class="status-pill">{ui.preparing}</span>{/if}</aside></section>
<section class="wrap curriculum"><div class="curriculum-tools"><h2>{ui.curriculum}</h2><div class="filter-group" aria-label={ui.levelFilter}>{#each ['all','A','AA','AAA'] as f}<button class:active={filter===f} aria-pressed={filter===f} onclick={()=>filter=f}>{f==='all'?ui.all:f}</button>{/each}</div></div>
 {#each groups as group}<section class="chapter-group"><div class="chapter-heading"><span class="eyebrow">{group.id==='intro'?'START':group.id==='outro'?'FINISH':'PRINCIPLE 0'+group.id}</span><h3>{group.name}</h3><p>{group.caption}</p></div><ol>{#each data.posts.filter(p=>p.group===group.id&&(filter==='all'||!p.level||p.level===filter)) as p}<li><span class="chapter-number">{String(p.order).padStart(2,'0')}</span><div><a href={localizedPath('/series/accessibility/'+p.slug,data.lang)}>{p.title}</a><p>{p.summary}</p></div><div class="chapter-tags">{#if p.criterion}<span>{p.criterion}</span><span>{p.level}</span>{/if}<span>{p.status==='published'&&p.available?ui.public:p.available?ui.draft:ui.planned}</span></div><a class="chapter-arrow" href={localizedPath('/series/accessibility/'+p.slug,data.lang)} aria-label={ui.read+': '+p.title}><Arrow/></a></li>{/each}</ol></section>{/each}
</section>
